[package]
name = "chain-signatures"
version = "0.1.3"
description = "Chain signatures program for cross-chain signing on Solana"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
repository = "https://github.com/esaminu/chain-signatures-solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "chain_signatures"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]


[dependencies]
anchor-lang = { version = "0.31.1", features = ["event-cpi"] }

