[package]
authors = ['GalacticCouncil']
edition = "2018"
name = "module-amm-rpc"
version = '1.0.0'

[dependencies.module-amm-rpc-runtime-api]
default-features = false
package = 'module-amm-rpc-runtime-api'
path = 'runtime-api'
version = '1.0.0'

[dependencies.serde]
default-features = false
features = ['derive']
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.1'

[dependencies.jsonrpc-core]
default-features = false
version = '14.0.3'

[dependencies.jsonrpc-core-client]
default-features = false
version = '14.0.3'

[dependencies.jsonrpc-derive]
default-features = false
version = '14.0.3'

[dependencies.sp-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-blockchain]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'

[features]
default = ['std']
std = [
  'codec/std',
]
