[package]
authors = ['GalacticCouncil']
description = 'HydraDX Exchange Module'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hack.hydradx-node'
license = 'Unlicense'
name = 'pallet-exchange'
repository = 'https://github.com/galacticcouncil/hack.hydradx-node'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
wasm-builder-runner = {package = 'substrate-wasm-builder-runner', version = '1.0.5'}

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
primitive-types = {default-features = false, version = '0.7.2'}
serde = {features = ['derive'], optional = true, version = '1.0.101'}

# Local dependencies
pallet-amm = {path = '../amm', default-features = false, version = '2.0.0'}
pallet-asset-registry = {path = '../asset-registry', default-features = false, version = '2.0.0'}
primitives = {path = '../../primitives', default-features = false, version = '2.0.0'}

# ORML dependencies
orml-tokens = {default-features = false, version = "0.3.2"}
orml-traits = {default-features = false, version = "0.3.2"}

# Substrate dependencies
frame-support = {default-features = false, version = '2.0.0'}
frame-system = {default-features = false, version = '2.0.0'}
sp-std = {default-features = false, version = '2.0.0'}

sp-core = {default-features = false, version = '2.0.0'}
sp-runtime = {default-features = false, version = '2.0.0'}

[dev-dependencies]
sp-io = {default-features = false, version = '2.0.0'}

[features]
default = ['std']
std = [
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'sp-std/std',
  'sp-runtime/std',
  'primitives/std',
  'orml-tokens/std',
  'orml-traits/std',
]
