[package]
name = "pallet-lbp"
version = "4.10.0"
description = "HydraDX Liquidity Bootstrapping Pool Pallet"
authors = ["GalacticCouncil"]
edition = "2021"
homepage = "https://github.com/galacticcouncil/hydradx-node"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/hydradx-node"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-wasm-builder = { workspace = true }

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
primitive-types = { workspace = true }
serde = { workspace = true, optional = true }

# HydraDX dependencies
hydra-dx-math = { workspace = true }
hydradx-traits = { workspace = true }
pallet-broadcast = { workspace = true }

## ORML dependencies
orml-traits = { workspace = true }

## Substrate dependencies
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-std = { workspace = true }

# Needed for benchmarks
orml-tokens = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

[dev-dependencies]
sp-io = { workspace = true }
test-utils = { workspace = true }
rug = { workspace = true }
proptest = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]
std = [
    "serde",
    "codec/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "orml-tokens/std",
    "orml-traits/std",
    "sp-runtime/std",
    "sp-core/std",
    "sp-std/std",
    "hydradx-traits/std",
    "frame-benchmarking/std",
    "scale-info/std",
    "hydra-dx-math/std",
    "pallet-broadcast/std",
]
try-runtime = ["frame-support/try-runtime"]
