[package]
name = "pallet-ismp-oracle-test"
version = "0.1.0"
authors = ['GalacticCouncil']
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/galacticcouncil/hydration-node'
repository = 'https://github.com/galacticcouncil/hydration-node'
description = "Pallet for dispatching ISMP get requests to get data from EVM chain"
readme = "README.md"

[dependencies]
# parity
codec = { workspace = true, features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true }
hex-literal = { workspace = true }

# primitives
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-core = { workspace = true }

# FRAME
frame-support = { workspace = true }
frame-system = { workspace = true }

# HydraDX dependencies
hydradx-traits = { workspace = true }

# ISMP dependencies
ismp = { workspace = true }
anyhow = { workspace = true }
pallet-ismp = { workspace = true }

# Optional imports for benchmarking
frame-benchmarking = { workspace = true, optional = true }

[features]
default = ['std']
std = [
    'anyhow/std',
    'codec/std',
    'scale-info/std',
    'sp-runtime/std',
    'sp-core/std',
    'sp-std/std',
    'frame-benchmarking/std',
    'hydradx-traits/std',
]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
