[package]
authors = ['GalacticCouncil']
description = 'HydraDX Exchange Benchmakring Module'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hydra-dx'
license = 'Unlicense'
name = 'pallet-exchange-benchmarking'
repository = 'https://github.com/galacticcouncil/hydra-dx'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
wasm-builder-runner = { package = 'substrate-wasm-builder-runner', version = '1.0.5' }

[dependencies]
serde = { features = ['derive'], optional = true, version = '1.0.101' }
codec = {package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive']}

# Local dependencies
primitives = { path = '../../../primitives', default-features = false, version = '3.0.0' }
pallet-asset-registry= { path = '../../asset-registry', default-features = false, version = '3.0.0' }
pallet-amm = { path = '../../amm', default-features = false, version = '3.0.0' }
pallet-exchange = { path = '../../exchange', default-features = false, version = '3.0.0' }

# ORML dependencies
orml-traits = { default-features = false, version = "0.4.0-dev" }
orml-tokens = { default-features = false, version = "0.4.0-dev" }

# Substrate dependencies
frame-system = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }
frame-benchmarking = { default-features = false, version = '3.0.0' }
frame-system-benchmarking = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }

sp-core = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }

[dev-dependencies]
sp-io = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'sp-std/std',
  'sp-runtime/std',
  'primitives/std',
  'pallet-exchange/std',
  'pallet-asset-registry/std',
  "frame-benchmarking/std",
]
