[package]
name = "pallet-xyk-liquidity-mining-benchmarking"
version = "1.0.16"
description = "Liquidity Mining Benchmarking Module"
authors = ["GalacticCouncil"]
edition = "2021"
homepage = "https://github.com/galacticcouncil/basilisk-node"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/basilisk-node"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", features = ["derive", "max-encoded-len"], default-features = false }
scale-info = { version = "2.3.1", features = ["derive"], default-features = false }

# Local dependencies
pallet-xyk-liquidity-mining = { path = "../../xyk-liquidity-mining", default-features = false }
primitives = { path = "../../../primitives", default-features = false }

# ORML dependencies
orml-traits = { workspace = true }
orml-tokens = { workspace = true }

# HydraDX dependencies
pallet-nft = { workspace = true }
pallet-asset-registry = { workspace = true }
pallet-liquidity-mining = { workspace = true }
hydradx-traits = { workspace = true }
pallet-duster = { workspace = true }
pallet-xyk = { workspace = true }

# Substrate dependencies
sp-std = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-arithmetic = { workspace = true }
pallet-uniques = { workspace = true }
pallet-balances = { workspace = true }

frame-benchmarking = { workspace = true }

[dev-dependencies]
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]

runtime-benchmarks=["pallet-uniques/runtime-benchmarks"]

std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "sp-std/std",
    "orml-traits/std",
    "orml-tokens/std",
    "primitives/std",
    "hydradx-traits/std",
    "pallet-balances/std",
    "frame-benchmarking/std",
    "pallet-xyk-liquidity-mining/std",
    "pallet-asset-registry/std",
    "pallet-nft/std",
    "pallet-uniques/std",
    "pallet-duster/std",
]
