[package]
name = "aave-simulator"
version = "1.0.0"
authors = ['GalacticCouncil']
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/galacticcouncil/hydration-node'
repository = 'https://github.com/galacticcouncil/hydration-node'
description = ""

[dependencies]
primitive-types = { workspace = true }
primitives = { workspace = true }
sp-arithmetic = { workspace = true }
module-evm-utility-macro = { workspace = true }
num_enum = { workspace = true }
codec = { workspace = true }
frame-support = { workspace = true }
ethabi = { workspace = true }
precompile-utils = { workspace = true }
evm = { workspace = true, features = ["with-codec"] }
hex-literal = { workspace = true }
log = { workspace = true }
hydra-dx-math = { workspace = true }
sp-std = { workspace = true }
pallet-liquidation = { workspace = true }

# Hydration dependencies
ice-support = { workspace = true }
hydradx-traits = { workspace = true }


[dev-dependencies]


[features]
default = ['std']
std = [
    'hydradx-traits/std',
    'primitive-types/std',
    'primitives/std',
    'sp-arithmetic/std',
    'codec/std',
    'frame-support/std',
    'ethabi/std',
    'precompile-utils/std',
    'evm/std',
    'hydra-dx-math/std',
    'sp-std/std',
    'pallet-liquidation/std',
]
